
name: macos-10.15

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  perl:
    # REF: https://github.com/actions/virtual-environments
    runs-on: macOS-10.15

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      # REF: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md (see link above, at the time of writing we get Perl 5.34.0 with macOS 10.15)
      - name: Set up Perl
        run: |
          brew install perl
          curl https://cpanmin.us | perl - App::cpanminus -n
          echo "/Users/runner/perl5/bin" >> $GITHUB_PATH
      - name: perl -V
        run: perl -V

      - name: Run Tests
        run: |
          curl -sL https://cpanmin.us/ | perl - -nq --with-develop --installdeps -v .
          perl Makefile.PL
          make
          make test
